spring:
  profiles:
    # dev or prod
    active: dev
    include: addi
  devtools:
    livereload:
      restart:
        enabled: 'true'
      enabled: 'true'
  output:
    ansi:
      enabled: always
